image: docker:24

services:
  - name: dind:24
    alias: docker

stages:
  - build

variables:
  BUILD_TAG: "${CI_COMMIT_REF_NAME}"

before_script:
  - echo "$CI_REGISTRY_PASSWORD" | docker login -u "$CI_REGISTRY_USER" "$CI_REGISTRY" --password-stdin
  - apk add make

build-ansible-images:
  stage: build
  script:
    - export BUILD_TAG="${MOLECULE_VERSION}-${ANSIBLE_BASE_IMAGE_VERSION}"
    - export MOLECULE_VERSION=${MOLECULE_VERSION}.*
    - make target=build docker-build
    - make target=build docker-push
  parallel:
    matrix:
      - ANSIBLE_BASE_IMAGE_VERSION: ['8']
        MOLECULE_VERSION: ['6']
