image: docker:24

services:
  - name: dind:24
    alias: docker

stages:
  - build

variables:
  BUILD_TAG: "${CI_COMMIT_REF_NAME}"

before_script:
  - echo "$CI_REGISTRY_PASSWORD" | docker login -u "$CI_REGISTRY_USER" "$CI_REGISTRY" --password-stdin
  - apk add make

build-ansible-images:
  stage: build
  script:
    - export ANSIBLE_BASE_IMAGE_VERSION=${ANSIBLE_BASE_IMAGE_VERSION}
    - make target=build docker-build
    - make target=build docker-push
  parallel:
    matrix:
      - ANSIBLE_BASE_IMAGE_VERSION: ['6', '7', '8']
