version: "3.8"

services:
  molecule:
    build:
      cache_from:
        - ${CI_REGISTRY}/${CI_PROJECT_NAMESPACE}/${CI_PROJECT_NAME}/molecule:${BUILD_TAG}
        - ${CI_REGISTRY}/${CI_PROJECT_NAMESPACE}/${CI_PROJECT_NAME}/molecule:${CI_DEFAULT_BRANCH}
        - ${CI_REGISTRY}/${CI_PROJECT_NAMESPACE}/${CI_PROJECT_NAME}/molecule:${CI_COMMIT_BRANCH}
    image: ${CI_REGISTRY}/${CI_PROJECT_NAMESPACE}/${CI_PROJECT_NAME}/molecule:${BUILD_TAG}
